### ISSUE TITLE
About btf2wit version

### ISSUE THREAD

**Issue by yaoyaoio** [eunomia-bpf/btf2wit#11]
I used `cargo install btf2wit`  the old version.
I think need update btf2wit to https://crates.io/crates/btf2wit.
What do you think?

**Comment by Officeyutong** [comment]
We have to wait for the new version of `btfdump` published to `crates.io`, or `btf2wit` on `crates.io` cannot use the new version of `btfdump`.

See https://github.com/anakryiko/btfdump/issues/5 for details.

**Comment by yaoyaoio** [comment]
I'm waiting.

**Comment by Officeyutong** [comment]
> I'm waiting.

I've just published version `0.1.2` to crates.io, which uses btfdump of version `0.0.2`. Check if this version works

**Comment by yaoyaoio** [comment]
I successfully tested in ubuntu(arm64).
Thank you.

**Comment by Officeyutong** [comment]
> I successfully tested in ubuntu(arm64). Thank you.

Thank you! I'll close this issue.
