### ISSUE TITLE
failed in install btf2wit 

### ISSUE THREAD

**Issue by yaoyaoio** [eunomia-bpf/btf2wit#9]
**Describe the bug**

```bash
cargo install btf2wit
```

```   Compiling btfdump v0.0.1
error[E0308]: mismatched types
    --> /home/yao/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/btfdump-0.0.1/src/types.rs:1538:45
     |
1538 |         let c_str = unsafe { CStr::from_ptr(&strs[off as usize] as *const u8 as *const i8) };
     |                              -------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
     |                              |
     |                              arguments to this function are incorrect
     |
     = note: expected raw pointer `*const u8`
                found raw pointer `*const i8`
note: associated function defined here
    --> /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ffi/c_str.rs:256:25

For more information about this error, try `rustc --explain E0308`.
error: could not compile `btfdump` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `btf2wit v0.1.1`, intermediate artifacts can be found at `/tmp/cargo-installpOisMF`
```

My Mac: `MacBook Pro (14-inch, 2021)`, `Version 13.2`, `M1 Max (ARM64,aarch64)`
My Develop: `Ubuntu 22.04.2 LTS (5.15.0-60-generic)`  in `Parallels Desktop 18 for Mac`

`cargo install btf2wit` in ubuntu.

rust verison:
```
rustc --version
rustc 1.67.1 (d5a82bbd2 2023-02-07)
```

**Comment by yaoyaoio** [comment]
So, what should i do?

**Comment by Officeyutong** [comment]
> So, what should i do?

Try reinstalling your toolchain.

Use `rustup toolchain list` to show which toolchain you are using. Then use `rustup toolchain uninstall [TOOLCHAIN]` to uninstall it, and use `rustup toolchain install [TOOLCHAIN]` to install it.

**Comment by yaoyaoio** [comment]
I installed rust on  a new ubuntu(arm64).
Still report failed.

**Comment by ocfox** [comment]
It could not be reproduced on my MacBook M1 and the installation was successful.

**Comment by ocfox** [comment]
Fixed at https://github.com/anakryiko/btfdump/pull/4

**Comment by yaoyaoio** [comment]
> > I installed rust on a new ubuntu(arm64).
> > Still report failed.
> 
> How did you install rust? If you have installed rust through apt, uninstall it and reinstall with rustup

I used `sudo curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Comment by yaoyaoio** [comment]
> Fixed at [anakryiko/btfdump#4](https://github.com/anakryiko/btfdump/pull/4)

Thank you for your fixed.
I wait for the PR to pass the test.

**Comment by ocfox** [comment]
Before #9 is merged, you can first use the branch https://github.com/eunomia-bpf/btf2wit/tree/btfdump, it should work.

**Comment by yaoyaoio** [comment]
> Before #9 is merged, you can first use the branch https://github.com/eunomia-bpf/btf2wit/tree/btfdump, it should work.

I gave it a try. is ok. no problom. thank you.
